on:
  github:
    branches:
      only: main
jobs:
  HelloWorld:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, World!"


#  on:
#   push:
#     branches:
#       - main
# jobs:
#   HelloWorld:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Print Hello World
#         run: echo "Hello, World!"
